version: "3"
services: 
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - Network1
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - Network1

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - Network1
  
networks:
  Network1:
    driver: bridge